// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCarData, CreateCarModelData, CreateCarModelResponses, CreateCarResponses, CreateClientData, CreateClientResponses, CreateMechanic1Data, CreateMechanic1Responses, CreateMechanicalConditionData, CreateMechanicalConditionResponses, CreateMechanicData, CreateMechanicResponses, CreateRecordData, CreateRecordResponses, CreateToolData, CreateToolResponses, GetAllCarBrandsData, GetAllCarBrandsResponses, GetAllCarModelsData, GetAllCarModelsResponses, GetAllCarsData, GetAllCarsResponses, GetAllClientsData, GetAllClientsResponses, GetAllMechanicsData, GetAllMechanicsResponses, GetAllRecordsData, GetAllRecordsResponses, GetAllToolsData, GetAllToolsResponses, GetCarFullData, GetCarFullResponses, GetCarModelData, GetCarModelResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllTools = <ThrowOnError extends boolean = false>(options?: Options<GetAllToolsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllToolsResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options
    });
};

export const createTool = <ThrowOnError extends boolean = false>(options: Options<CreateToolData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateToolResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllRecords = <ThrowOnError extends boolean = false>(options?: Options<GetAllRecordsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllRecordsResponses, unknown, ThrowOnError>({
        url: '/api/record',
        ...options
    });
};

export const createRecord = <ThrowOnError extends boolean = false>(options: Options<CreateRecordData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateRecordResponses, unknown, ThrowOnError>({
        url: '/api/record',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const createMechanicalCondition = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicalConditionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicalConditionResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllMechanics = <ThrowOnError extends boolean = false>(options?: Options<GetAllMechanicsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllMechanicsResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options
    });
};

export const createMechanic = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllClients = <ThrowOnError extends boolean = false>(options?: Options<GetAllClientsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllClientsResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options
    });
};

export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateClientResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCars = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarsResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options
    });
};

export const createCar = <ThrowOnError extends boolean = false>(options: Options<CreateCarData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarModels = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarModelsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarModelsResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options
    });
};

export const createCarModel = <ThrowOnError extends boolean = false>(options: Options<CreateCarModelData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarBrands = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarBrandsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarBrandsResponses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options
    });
};

export const createMechanic1 = <ThrowOnError extends boolean = false>(options: Options<CreateMechanic1Data, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanic1Responses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getCarFull = <ThrowOnError extends boolean = false>(options: Options<GetCarFullData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarFullResponses, unknown, ThrowOnError>({
        url: '/api/car/{id}',
        ...options
    });
};

export const getCarModel = <ThrowOnError extends boolean = false>(options: Options<GetCarModelData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model/{id}',
        ...options
    });
};
