// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCarData, CreateCarModelData, CreateCarModelResponses, CreateCarResponses, CreateCheckInData, CreateCheckInResponses, CreateClientData, CreateClientResponses, CreateData, CreateErrors, CreateFullData, CreateFullResponses, CreateMechanic1Data, CreateMechanic1Responses, CreateMechanicalConditionData, CreateMechanicalConditionResponses, CreateMechanicData, CreateMechanicResponses, CreateResponses, CreateToolData, CreateToolResponses, GetAllCarBrandsData, GetAllCarBrandsResponses, GetAllCarModelsData, GetAllCarModelsResponses, GetAllCarsData, GetAllCarsResponses, GetAllCheckInFullData, GetAllCheckInFullResponses, GetAllClientsData, GetAllClientsResponses, GetAllMechanicsData, GetAllMechanicsResponses, GetAllPatentsData, GetAllPatentsResponses, GetAllToolsData, GetAllToolsResponses, GetAllWorkOrdersData, GetAllWorkOrdersResponses, GetAllWorkServicesData, GetAllWorkServicesResponses, GetCarFullByIdData, GetCarFullByIdResponses, GetCarFullByPatentData, GetCarFullByPatentResponses, GetCarModelData, GetCarModelResponses, GetCheckInFullData, GetCheckInFullResponses, GetElectricalConditionsData, GetElectricalConditionsResponses, GetExteriorConditionsData, GetExteriorConditionsResponses, GetImageCategoryData, GetImageCategoryResponses, GetInteriorConditionsData, GetInteriorConditionsResponses, GetWorkOrderFullByIdData, GetWorkOrderFullByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Retrieve all work services
 *
 * Returns a list of all existing work services.
 */
export const getAllWorkServices = <ThrowOnError extends boolean = false>(options?: Options<GetAllWorkServicesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllWorkServicesResponses, unknown, ThrowOnError>({
        url: '/api/work-services',
        ...options
    });
};

/**
 * Create a new work service
 *
 * Creates a new service specifying its name and estimated duration.
 */
export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
        url: '/api/work-services',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create a full work order
 *
 * Send a multipart request: the 'payload' part must be application/json (the JSON body), and carPictures/signature as file parts.
 */
export const createFull = <ThrowOnError extends boolean = false>(options?: Options<CreateFullData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateFullResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/work-orders/full',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const getAllTools = <ThrowOnError extends boolean = false>(options?: Options<GetAllToolsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllToolsResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options
    });
};

export const createTool = <ThrowOnError extends boolean = false>(options: Options<CreateToolData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateToolResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const createMechanicalCondition = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicalConditionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicalConditionResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllMechanics = <ThrowOnError extends boolean = false>(options?: Options<GetAllMechanicsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllMechanicsResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options
    });
};

export const createMechanic = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllClients = <ThrowOnError extends boolean = false>(options?: Options<GetAllClientsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllClientsResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options
    });
};

export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateClientResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCheckInFull = <ThrowOnError extends boolean = false>(options?: Options<GetAllCheckInFullData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCheckInFullResponses, unknown, ThrowOnError>({
        url: '/api/checkin',
        ...options
    });
};

export const createCheckIn = <ThrowOnError extends boolean = false>(options: Options<CreateCheckInData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCheckInResponses, unknown, ThrowOnError>({
        url: '/api/checkin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCars = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarsResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options
    });
};

export const createCar = <ThrowOnError extends boolean = false>(options: Options<CreateCarData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarModels = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarModelsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarModelsResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options
    });
};

export const createCarModel = <ThrowOnError extends boolean = false>(options: Options<CreateCarModelData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarBrands = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarBrandsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarBrandsResponses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options
    });
};

export const createMechanic1 = <ThrowOnError extends boolean = false>(options: Options<CreateMechanic1Data, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanic1Responses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get all work orders
 *
 * Returns a list of all work orders.
 */
export const getAllWorkOrders = <ThrowOnError extends boolean = false>(options?: Options<GetAllWorkOrdersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllWorkOrdersResponses, unknown, ThrowOnError>({
        url: '/api/work-orders',
        ...options
    });
};

/**
 * Get full work order by ID
 *
 * Obtiene todos los datos detallados de la orden de trabajo por su ID.
 */
export const getWorkOrderFullById = <ThrowOnError extends boolean = false>(options: Options<GetWorkOrderFullByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetWorkOrderFullByIdResponses, unknown, ThrowOnError>({
        url: '/api/work-orders/{id}/full',
        ...options
    });
};

export const getInteriorConditions = <ThrowOnError extends boolean = false>(options?: Options<GetInteriorConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInteriorConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/interior',
        ...options
    });
};

export const getExteriorConditions = <ThrowOnError extends boolean = false>(options?: Options<GetExteriorConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetExteriorConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/exterior',
        ...options
    });
};

export const getElectricalConditions = <ThrowOnError extends boolean = false>(options?: Options<GetElectricalConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetElectricalConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/electrical',
        ...options
    });
};

export const getImageCategory = <ThrowOnError extends boolean = false>(options?: Options<GetImageCategoryData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetImageCategoryResponses, unknown, ThrowOnError>({
        url: '/api/dashboard-lights',
        ...options
    });
};

export const getCheckInFull = <ThrowOnError extends boolean = false>(options: Options<GetCheckInFullData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCheckInFullResponses, unknown, ThrowOnError>({
        url: '/api/checkin/{id}/full',
        ...options
    });
};

export const getCarFullById = <ThrowOnError extends boolean = false>(options: Options<GetCarFullByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarFullByIdResponses, unknown, ThrowOnError>({
        url: '/api/car/{id}',
        ...options
    });
};

export const getAllPatents = <ThrowOnError extends boolean = false>(options?: Options<GetAllPatentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllPatentsResponses, unknown, ThrowOnError>({
        url: '/api/car/patents',
        ...options
    });
};

export const getCarFullByPatent = <ThrowOnError extends boolean = false>(options: Options<GetCarFullByPatentData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarFullByPatentResponses, unknown, ThrowOnError>({
        url: '/api/car/by-patent/{patent}',
        ...options
    });
};

export const getCarModel = <ThrowOnError extends boolean = false>(options: Options<GetCarModelData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model/{id}',
        ...options
    });
};
