// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { Create1Data, Create1Responses, CreateCarData, CreateCarModelData, CreateCarModelResponses, CreateCarResponses, CreateCheckInData, CreateCheckInResponses, CreateClientData, CreateClientResponses, CreateData, CreateFullData, CreateFullResponses, CreateMechanic1Data, CreateMechanic1Responses, CreateMechanicalConditionData, CreateMechanicalConditionResponses, CreateMechanicData, CreateMechanicResponses, CreateRecordData, CreateRecordResponses, CreateResponses, CreateToolData, CreateToolResponses, Get1Data, Get1Responses, GetAll1Data, GetAll1Responses, GetAllCarBrandsData, GetAllCarBrandsResponses, GetAllCarModelsData, GetAllCarModelsResponses, GetAllCarsData, GetAllCarsResponses, GetAllCheckInFullData, GetAllCheckInFullResponses, GetAllClientsData, GetAllClientsResponses, GetAllData, GetAllMechanicsData, GetAllMechanicsResponses, GetAllPatentsData, GetAllPatentsResponses, GetAllRecordsData, GetAllRecordsResponses, GetAllResponses, GetAllToolsData, GetAllToolsResponses, GetCarFullByIdData, GetCarFullByIdResponses, GetCarFullByPatentData, GetCarFullByPatentResponses, GetCarModelData, GetCarModelResponses, GetCheckInFullData, GetCheckInFullResponses, GetData, GetElectricalConditionsData, GetElectricalConditionsResponses, GetExteriorConditionsData, GetExteriorConditionsResponses, GetInteriorConditionsData, GetInteriorConditionsResponses, GetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const createFull = <ThrowOnError extends boolean = false>(options: Options<CreateFullData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateFullResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/work-orders/full',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

export const getAllTools = <ThrowOnError extends boolean = false>(options?: Options<GetAllToolsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllToolsResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options
    });
};

export const createTool = <ThrowOnError extends boolean = false>(options: Options<CreateToolData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateToolResponses, unknown, ThrowOnError>({
        url: '/api/tool',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllRecords = <ThrowOnError extends boolean = false>(options?: Options<GetAllRecordsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllRecordsResponses, unknown, ThrowOnError>({
        url: '/api/record',
        ...options
    });
};

export const createRecord = <ThrowOnError extends boolean = false>(options: Options<CreateRecordData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateRecordResponses, unknown, ThrowOnError>({
        url: '/api/record',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAll = <ThrowOnError extends boolean = false>(options?: Options<GetAllData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllResponses, unknown, ThrowOnError>({
        url: '/api/picture',
        ...options
    });
};

export const create = <ThrowOnError extends boolean = false>(options?: Options<CreateData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/picture',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const createMechanicalCondition = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicalConditionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicalConditionResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllMechanics = <ThrowOnError extends boolean = false>(options?: Options<GetAllMechanicsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllMechanicsResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options
    });
};

export const createMechanic = <ThrowOnError extends boolean = false>(options: Options<CreateMechanicData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanicResponses, unknown, ThrowOnError>({
        url: '/api/mechanic',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAll1 = <ThrowOnError extends boolean = false>(options?: Options<GetAll1Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAll1Responses, unknown, ThrowOnError>({
        url: '/api/dashboard-lights',
        ...options
    });
};

export const create1 = <ThrowOnError extends boolean = false>(options?: Options<Create1Data, ThrowOnError>) => {
    return (options?.client ?? client).post<Create1Responses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/dashboard-lights',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const getAllClients = <ThrowOnError extends boolean = false>(options?: Options<GetAllClientsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllClientsResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options
    });
};

export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateClientResponses, unknown, ThrowOnError>({
        url: '/api/client-info',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCheckInFull = <ThrowOnError extends boolean = false>(options?: Options<GetAllCheckInFullData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCheckInFullResponses, unknown, ThrowOnError>({
        url: '/api/checkin',
        ...options
    });
};

export const createCheckIn = <ThrowOnError extends boolean = false>(options: Options<CreateCheckInData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCheckInResponses, unknown, ThrowOnError>({
        url: '/api/checkin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCars = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarsResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options
    });
};

export const createCar = <ThrowOnError extends boolean = false>(options: Options<CreateCarData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarResponses, unknown, ThrowOnError>({
        url: '/api/car',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarModels = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarModelsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarModelsResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options
    });
};

export const createCarModel = <ThrowOnError extends boolean = false>(options: Options<CreateCarModelData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllCarBrands = <ThrowOnError extends boolean = false>(options?: Options<GetAllCarBrandsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllCarBrandsResponses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options
    });
};

export const createMechanic1 = <ThrowOnError extends boolean = false>(options: Options<CreateMechanic1Data, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMechanic1Responses, unknown, ThrowOnError>({
        url: '/api/car-brand',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const get = <ThrowOnError extends boolean = false>(options: Options<GetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetResponses, unknown, ThrowOnError>({
        url: '/api/picture/{id}',
        ...options
    });
};

export const getInteriorConditions = <ThrowOnError extends boolean = false>(options?: Options<GetInteriorConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInteriorConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/interior',
        ...options
    });
};

export const getExteriorConditions = <ThrowOnError extends boolean = false>(options?: Options<GetExteriorConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetExteriorConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/exterior',
        ...options
    });
};

export const getElectricalConditions = <ThrowOnError extends boolean = false>(options?: Options<GetElectricalConditionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetElectricalConditionsResponses, unknown, ThrowOnError>({
        url: '/api/mechanical-condition/electrical',
        ...options
    });
};

export const get1 = <ThrowOnError extends boolean = false>(options: Options<Get1Data, ThrowOnError>) => {
    return (options.client ?? client).get<Get1Responses, unknown, ThrowOnError>({
        url: '/api/dashboard-lights/{id}',
        ...options
    });
};

export const getCheckInFull = <ThrowOnError extends boolean = false>(options: Options<GetCheckInFullData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCheckInFullResponses, unknown, ThrowOnError>({
        url: '/api/checkin/{id}/full',
        ...options
    });
};

export const getCarFullById = <ThrowOnError extends boolean = false>(options: Options<GetCarFullByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarFullByIdResponses, unknown, ThrowOnError>({
        url: '/api/car/{id}',
        ...options
    });
};

export const getAllPatents = <ThrowOnError extends boolean = false>(options?: Options<GetAllPatentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllPatentsResponses, unknown, ThrowOnError>({
        url: '/api/car/patents',
        ...options
    });
};

export const getCarFullByPatent = <ThrowOnError extends boolean = false>(options: Options<GetCarFullByPatentData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarFullByPatentResponses, unknown, ThrowOnError>({
        url: '/api/car/by-patent/{patent}',
        ...options
    });
};

export const getCarModel = <ThrowOnError extends boolean = false>(options: Options<GetCarModelData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCarModelResponses, unknown, ThrowOnError>({
        url: '/api/car-model/{id}',
        ...options
    });
};
