// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type GetService = {
    /**
     * ID del servicio
     */
    id: number;
    /**
     * Nombre del servicio
     */
    name: string;
    /**
     * Tiempo estimado en formato HH:mm[:ss]
     */
    estimatedTime: string;
};

export type CreateWorkServiceRequest = {
    /**
     * Nombre del servicio (máx 32 caracteres)
     */
    serviceName: string;
    /**
     * Tiempo estimado en formato HH:mm o HH:mm:ss
     */
    estimatedTime: string;
};

export type CreateMechanicRequest = {
    name?: string;
    rut?: string;
};

export type CreateWorkOrderHasDashboardLightRequest = {
    /**
     * ID del dashboard light
     */
    dashboardLightId: number;
    /**
     * Si el dashboard light está presente (default false)
     */
    present: boolean;
    /**
     * Si el dashboard light opera correctamente (default false)
     */
    isFunctional: boolean;
};

/**
 * JSON payload describing the work order (application/json).
 */
export type CreateWorkOrderRequest = {
    /**
     * Associated record ID
     */
    recordId: number;
    /**
     * Existing service IDs
     */
    serviceIds?: Array<number>;
    /**
     * New services to be created
     */
    newServices?: Array<CreateWorkServiceRequest>;
    /**
     * Dashboard lights to associate
     */
    dashboardLightsActive?: Array<CreateWorkOrderHasDashboardLightRequest>;
    /**
     * Mechanic IDs to associate with the order
     */
    mechanicIds: Array<number>;
    /**
     * New mechanics to be created
     */
    newMechanics: Array<CreateMechanicRequest>;
    /**
     * ID of the mechanic who will be the leader
     */
    leaderMechanicId?: number;
    /**
     * New mechanics to be created
     */
    newLeaderMechanic?: CreateMechanicRequest;
};

/**
 * WorkOrder Response
 */
export type CreateWorkOrderResponse = {
    /**
     * ID of the created work order
     */
    id?: number;
    /**
     * Associated record ID
     */
    recordId?: number;
    /**
     * Created date in yyyy-MM-dd format
     */
    cratedAt?: string;
    /**
     * Estimated delivery date in yyyy-MM-dd format
     */
    estimatedDelivery?: string;
    /**
     * Path to the signature file
     */
    signaturePath?: string;
};

export type CreateToolRequest = {
    name: string;
};

export type SingleToolResponse = {
    id: number;
    name: string;
};

export type CreateMechanicalConditionRequest = {
    partName?: string;
    partConditionState?: string;
    conditionType?: string;
};

export type CreateMechanicalConditionResponse = {
    id?: number;
    part_name?: string;
    part_condition_state?: string;
    condition_type?: string;
};

export type CreateMechanicResponse = {
    id?: number;
    rut?: string;
};

export type CreateClientRequest = {
    firstName: string;
    rut: string;
    lastName?: string;
    emailAddress: string;
    address: string;
    cellphoneNumber: string;
};

export type CreateClientResponse = {
    id?: number;
    cellphone_name?: string;
};

export type CreateCarBrandRequest = {
    brandName?: string;
};

export type CreateCarCheckInRequest = {
    VIN: string;
    licensePlate: string;
};

export type CreateCarModelCheckInRequest = {
    modelName: string;
    modelType: string;
    modelYear?: number;
};

export type CreateCheckInRequest = {
    clientId?: number;
    client?: CreateClientRequest;
    carId?: number;
    car?: CreateCarCheckInRequest;
    carModelID?: number;
    carModel?: CreateCarModelCheckInRequest;
    carBrandID?: number;
    carBrand?: CreateCarBrandRequest;
    interiorConditionsIds: Array<number>;
    exteriorConditionsIds: Array<number>;
    electricalConditionsIds: Array<number>;
    toolsIds: Array<number>;
    newTools: Array<CreateToolRequest>;
    reason: string;
    recordState: CreateRecordStateRequest;
    gasLevel: string;
    valuables?: string;
    observations?: string;
};

export type CreateRecordStateRequest = {
    /**
     * Kilometraje (entero >= 0)
     */
    mileage: number;
};

export type CreateCheckInResponse = {
    id?: number;
    entry_time?: string;
    mileage?: number;
    gas_level?: string;
    valuables?: string;
    client_id?: number;
    car_id?: number;
    mechanical_conditions_ids?: Array<number>;
    tools_ids?: Array<number>;
};

export type CreateCarRequest = {
    VIN: string;
    licensePlate: string;
    modelId?: number;
};

export type CreateCarResponse = {
    id?: number;
    licensePlate?: string;
};

export type CreateCarModelRequest = {
    modelName: string;
    modelType: string;
    modelYear?: number;
    brandId?: number;
};

export type CreateCarModelResponse = {
    id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
};

export type CreateCarBrandResponse = {
    id?: number;
    registration_number?: string;
};

export type TrimmedWorkOrder = {
    id: number;
    isCompleted: boolean;
    createdAt: string;
    deliveryTime: string;
    signatureUrl: string;
    mechanicLeaderFullName: string;
    clientFirstName: string;
    clientLastName: string;
    clientCellphoneNumber: string;
    carLicensePlate: string;
};

export type Client = {
    id: number;
    firstName: string;
    rut: string;
    lastName: string;
    emailAddress: string;
    address: string;
    cellphoneNumber: string;
};

export type GetCar = {
    id: number;
    VIN: string;
    licensePlate: string;
    modelId: number;
    modelName: string;
    modelType: string;
    modelYear: number;
    brandId: number;
    brandName: string;
};

export type GetImage = {
    id: number;
    url: string;
    alt: string;
};

export type GetMechanicWorkOrder = {
    id: number;
    name: string;
    rut: string;
    isLeader: boolean;
};

export type GetWorkOrderFull = {
    id?: number;
    createdAt?: string;
    estimatedDelivery?: string;
    services?: Array<GetService>;
    mechanics?: Array<GetMechanicWorkOrder>;
    signatureUrl?: string;
    carImages?: Array<GetImage>;
    dashboardLights?: Array<GetWorkOrderHasDashboardLight>;
    customer?: Client;
    vehicle?: GetCar;
};

export type GetWorkOrderHasDashboardLight = {
    imageId: number;
    url: string;
    alt: string;
    isFunctional: boolean;
};

export type SingleMechanicalCondition = {
    id: number;
    partName: string;
    conditionState: string;
};

export type GetMechanicInfo = {
    id: number;
    name: string;
    rut: string;
};

export type ClientInfo = {
    id?: number;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    address?: string;
    cellphoneNumber?: string;
    rut: string;
};

export type GetCheckInBasicResponse = {
    checkInId: number;
    clientName: string;
    clientEmail: string;
    brandName: string;
    modelName: string;
    modelType: string;
    modelYear: number;
    licensePlate: string;
    reason: string;
    observations: string;
    conditions: Array<MechanicalCondition>;
    entryTime: string;
};

export type MechanicalCondition = {
    partName: string;
    state: string;
};

export type GetCheckInFullResponse = {
    /**
     * Record id
     */
    recordId?: number;
    /**
     * Check-in id
     */
    checkInId?: number;
    /**
     * Client id
     */
    clientId?: number;
    /**
     * Client full name
     */
    clientName?: string;
    /**
     * Client email
     */
    clientEmail?: string;
    /**
     * Car brand name
     */
    brandName?: string;
    /**
     * Car model name
     */
    modelName?: string;
    /**
     * Car model type
     */
    modelType?: string;
    /**
     * Car model year
     */
    modelYear?: number;
    /**
     * Car license plate
     */
    licensePlate?: string;
    /**
     * Record reason
     */
    reason?: string;
    observations: string;
    /**
     * Mechanical conditions (id, type, part name, part state)
     */
    mechanicalConditions?: Array<MechanicalConditionInfo>;
    /**
     * Tools names
     */
    tools?: Array<string>;
    /**
     * Entry time as ISO datetime string
     */
    entryTime?: string;
    /**
     * Mileage
     */
    mileage?: number;
    /**
     * Gas level
     */
    gasLevel?: string;
    /**
     * Valuables declared
     */
    valuables?: string;
};

/**
 * Mechanical condition info (id, type, part name and part state)
 */
export type MechanicalConditionInfo = {
    /**
     * Condition id in its own table
     */
    id?: number;
    /**
     * Condition type: 'exterior'|'interior'|'electrical'
     */
    type?: string;
    /**
     * Part name
     */
    partName?: string;
    /**
     * Part condition state
     */
    partState?: string;
};

export type GetCarResponse = {
    id: number;
    VIN: string;
    licensePlate: string;
    modelId: number;
    modelName: string;
};

export type GetCarModelResponse = {
    id: number;
    modelName: string;
    modelType: string;
    modelYear: number;
    brandId: number;
    brandName: string;
};

export type SingleCarBrandResponse = {
    id: number;
    brandName: string;
};

export type GetAllWorkServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/work-services';
};

export type GetAllWorkServicesResponses = {
    /**
     * List returned successfully
     */
    200: Array<GetService>;
};

export type GetAllWorkServicesResponse = GetAllWorkServicesResponses[keyof GetAllWorkServicesResponses];

export type CreateData = {
    body: CreateWorkServiceRequest;
    path?: never;
    query?: never;
    url: '/api/work-services';
};

export type CreateErrors = {
    /**
     * Validation error
     */
    400: GetService;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Service created successfully
     */
    200: GetService;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type CreateFullData = {
    body?: {
        payload: CreateWorkOrderRequest;
        /**
         * Optional car pictures (one or more files). Send multiple parts named 'carPictures'.
         */
        carPictures?: Array<Blob | File>;
        /**
         * Mechanic signature image (single file)
         */
        signature?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/work-orders/full';
};

export type CreateFullResponses = {
    /**
     * OK
     */
    200: CreateWorkOrderResponse;
};

export type CreateFullResponse = CreateFullResponses[keyof CreateFullResponses];

export type GetAllToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type GetAllToolsResponses = {
    /**
     * OK
     */
    200: Array<SingleToolResponse>;
};

export type GetAllToolsResponse = GetAllToolsResponses[keyof GetAllToolsResponses];

export type CreateToolData = {
    body: CreateToolRequest;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type CreateToolResponses = {
    /**
     * OK
     */
    200: SingleToolResponse;
};

export type CreateToolResponse = CreateToolResponses[keyof CreateToolResponses];

export type CreateMechanicalConditionData = {
    body: CreateMechanicalConditionRequest;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition';
};

export type CreateMechanicalConditionResponses = {
    /**
     * OK
     */
    200: CreateMechanicalConditionResponse;
};

export type CreateMechanicalConditionResponse2 = CreateMechanicalConditionResponses[keyof CreateMechanicalConditionResponses];

export type GetAllMechanicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type GetAllMechanicsResponses = {
    /**
     * OK
     */
    200: Array<GetMechanicInfo>;
};

export type GetAllMechanicsResponse = GetAllMechanicsResponses[keyof GetAllMechanicsResponses];

export type CreateMechanicData = {
    body: CreateMechanicRequest;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type CreateMechanicResponses = {
    /**
     * OK
     */
    200: CreateMechanicResponse;
};

export type CreateMechanicResponse2 = CreateMechanicResponses[keyof CreateMechanicResponses];

export type GetAllClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type GetAllClientsResponses = {
    /**
     * OK
     */
    200: Array<ClientInfo>;
};

export type GetAllClientsResponse = GetAllClientsResponses[keyof GetAllClientsResponses];

export type CreateClientData = {
    body: CreateClientRequest;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type CreateClientResponses = {
    /**
     * OK
     */
    200: CreateClientResponse;
};

export type CreateClientResponse2 = CreateClientResponses[keyof CreateClientResponses];

export type GetAllCheckInFullData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/checkin';
};

export type GetAllCheckInFullResponses = {
    /**
     * OK
     */
    200: Array<GetCheckInBasicResponse>;
};

export type GetAllCheckInFullResponse = GetAllCheckInFullResponses[keyof GetAllCheckInFullResponses];

export type CreateCheckInData = {
    body: CreateCheckInRequest;
    path?: never;
    query?: never;
    url: '/api/checkin';
};

export type CreateCheckInResponses = {
    /**
     * OK
     */
    200: CreateCheckInResponse;
};

export type CreateCheckInResponse2 = CreateCheckInResponses[keyof CreateCheckInResponses];

export type GetAllCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type GetAllCarsResponses = {
    /**
     * OK
     */
    200: Array<GetCarResponse>;
};

export type GetAllCarsResponse = GetAllCarsResponses[keyof GetAllCarsResponses];

export type CreateCarData = {
    body: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type CreateCarResponses = {
    /**
     * OK
     */
    200: CreateCarResponse;
};

export type CreateCarResponse2 = CreateCarResponses[keyof CreateCarResponses];

export type GetAllCarModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type GetAllCarModelsResponses = {
    /**
     * OK
     */
    200: Array<GetCarModelResponse>;
};

export type GetAllCarModelsResponse = GetAllCarModelsResponses[keyof GetAllCarModelsResponses];

export type CreateCarModelData = {
    body: CreateCarModelRequest;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type CreateCarModelResponses = {
    /**
     * OK
     */
    200: CreateCarModelResponse;
};

export type CreateCarModelResponse2 = CreateCarModelResponses[keyof CreateCarModelResponses];

export type GetAllCarBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type GetAllCarBrandsResponses = {
    /**
     * OK
     */
    200: Array<SingleCarBrandResponse>;
};

export type GetAllCarBrandsResponse = GetAllCarBrandsResponses[keyof GetAllCarBrandsResponses];

export type CreateMechanic1Data = {
    body: CreateCarBrandRequest;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type CreateMechanic1Responses = {
    /**
     * OK
     */
    200: CreateCarBrandResponse;
};

export type CreateMechanic1Response = CreateMechanic1Responses[keyof CreateMechanic1Responses];

export type GetAllWorkOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/work-orders';
};

export type GetAllWorkOrdersResponses = {
    /**
     * OK
     */
    200: Array<TrimmedWorkOrder>;
};

export type GetAllWorkOrdersResponse = GetAllWorkOrdersResponses[keyof GetAllWorkOrdersResponses];

export type GetWorkOrderFullByIdData = {
    body?: never;
    path: {
        /**
         * ID de la orden de trabajo
         */
        id: number;
    };
    query?: never;
    url: '/api/work-orders/{id}/full';
};

export type GetWorkOrderFullByIdResponses = {
    /**
     * OK
     */
    200: GetWorkOrderFull;
};

export type GetWorkOrderFullByIdResponse = GetWorkOrderFullByIdResponses[keyof GetWorkOrderFullByIdResponses];

export type GetInteriorConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/interior';
};

export type GetInteriorConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetInteriorConditionsResponse = GetInteriorConditionsResponses[keyof GetInteriorConditionsResponses];

export type GetExteriorConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/exterior';
};

export type GetExteriorConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetExteriorConditionsResponse = GetExteriorConditionsResponses[keyof GetExteriorConditionsResponses];

export type GetElectricalConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/electrical';
};

export type GetElectricalConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetElectricalConditionsResponse = GetElectricalConditionsResponses[keyof GetElectricalConditionsResponses];

export type GetImageCategoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard-lights';
};

export type GetImageCategoryResponses = {
    /**
     * OK
     */
    200: Array<GetImage>;
};

export type GetImageCategoryResponse = GetImageCategoryResponses[keyof GetImageCategoryResponses];

export type GetCheckInFullData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/checkin/{id}/full';
};

export type GetCheckInFullResponses = {
    /**
     * OK
     */
    200: GetCheckInFullResponse;
};

export type GetCheckInFullResponse2 = GetCheckInFullResponses[keyof GetCheckInFullResponses];

export type GetCarFullByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car/{id}';
};

export type GetCarFullByIdResponses = {
    /**
     * OK
     */
    200: GetCar;
};

export type GetCarFullByIdResponse = GetCarFullByIdResponses[keyof GetCarFullByIdResponses];

export type GetAllPatentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car/patents';
};

export type GetAllPatentsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetAllPatentsResponse = GetAllPatentsResponses[keyof GetAllPatentsResponses];

export type GetCarFullByPatentData = {
    body?: never;
    path: {
        patent: string;
    };
    query?: never;
    url: '/api/car/by-patent/{patent}';
};

export type GetCarFullByPatentResponses = {
    /**
     * OK
     */
    200: GetCar;
};

export type GetCarFullByPatentResponse = GetCarFullByPatentResponses[keyof GetCarFullByPatentResponses];

export type GetCarModelData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car-model/{id}';
};

export type GetCarModelResponses = {
    /**
     * OK
     */
    200: GetCarModelResponse;
};

export type GetCarModelResponse2 = GetCarModelResponses[keyof GetCarModelResponses];
