// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateToolRequest = {
    name: string;
};

export type SingleToolResponse = {
    id: number;
    name: string;
};

export type CreateRecordRequest = {
    reason?: string;
    car_id?: number;
    client_info_id?: number;
    mechanic_info_id?: number;
};

export type CreateRecordResponse = {
    id?: number;
    car_id?: number;
    client_info_id?: number;
    mechanic_info_id?: number;
};

export type CreateMechanicalConditionRequest = {
    partName?: string;
    partConditionState?: string;
    conditionType?: string;
};

export type CreateMechanicalConditionResponse = {
    id?: number;
    part_name?: string;
    part_condition_state?: string;
    condition_type?: string;
};

export type CreateMechanicRequest = {
    first_name?: string;
    last_name?: string;
    registration_number?: string;
};

export type CreateMechanicResponse = {
    id?: number;
    registration_number?: string;
};

export type CreateClientRequest = {
    firstName: string;
    rut: string;
    lastName: string;
    emailAddress: string;
    address: string;
    cellphoneNumber: string;
};

export type CreateClientResponse = {
    id?: number;
    cellphone_name?: string;
};

export type CreateCarBrandRequest = {
    brandName?: string;
};

export type CreateCarModelRequest = {
    modelName: string;
    modelType: string;
    modelYear?: number;
    brandId?: number;
};

export type CreateCarRequest = {
    VIN: string;
    licensePlate: string;
    modelId?: number;
};

export type CreateCheckInRequest = {
    clientId?: number;
    client?: CreateClientRequest;
    carId?: number;
    car?: CreateCarRequest;
    carModel?: CreateCarModelRequest;
    carBrand?: CreateCarBrandRequest;
    mechanicalConditionsIds: Array<number>;
    toolsIds: Array<number>;
    newTools: Array<CreateToolRequest>;
    reason: string;
    recordState: CreateRecordStateRequest;
    gasLevel: string;
    valuables?: string;
};

export type CreateRecordStateRequest = {
    entryDate: string;
    entryTime: string;
    mileage: number;
};

export type CreateCheckInResponse = {
    id?: number;
    entry_date?: string;
    entry_time?: string;
    mileage?: number;
    gas_level?: string;
    valuables?: string;
    client_id?: number;
    car_id?: number;
    mechanical_conditions_ids?: Array<number>;
    tools_ids?: Array<number>;
};

export type CreateCarResponse = {
    id?: number;
    license_plate?: string;
};

export type CreateCarModelResponse = {
    id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
};

export type CreateCarBrandResponse = {
    id?: number;
    registration_number?: string;
};

export type GetRecordResponse = {
    reason?: string;
    car_license_plate?: string;
    client_first_name?: string;
    mechanic_first_name?: string;
};

export type SingleMechanicalCondition = {
    id: number;
    partName: string;
    conditionState: string;
};

export type MechanicInfo = {
    id?: number;
    firstName?: string;
    lastName?: string;
    registrationNumber?: string;
};

export type ClientInfo = {
    id?: number;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    address?: string;
    cellphoneNumber?: string;
};

export type GetCheckInBasicResponse = {
    checkInId?: number;
    clientName?: string;
    clientEmail?: string;
    brandName?: string;
    modelName?: string;
    modelType?: string;
    modelYear?: number;
    licensePlate?: string;
    reason?: string;
    mechanicalConditionPartNames?: Array<string>;
    mechanicalConditionStates?: Array<string>;
    entryDate?: string;
    entryTime?: string;
};

export type GetCheckInFullResponse = {
    checkInId?: number;
    clientId?: number;
    clientName?: string;
    clientEmail?: string;
    brandName?: string;
    modelName?: string;
    modelType?: string;
    modelYear?: number;
    licensePlate?: string;
    reason?: string;
    mechanicalConditionPartNames?: Array<string>;
    mechanicalConditionStates?: Array<string>;
    toolNames?: Array<string>;
    entryDate?: string;
    entryTime?: string;
    mileage?: number;
    gasLevel?: string;
    valuables?: string;
};

export type GetCarResponse = {
    id: number;
    VIN: string;
    licensePlate: string;
    modelId: number;
    modelName: string;
};

export type GetCarFullResponse = {
    id: number;
    VIN: string;
    licensePlate: string;
    modelId: number;
    modelName: string;
    modelType: string;
    modelYear: number;
    brandId: number;
    brandName: string;
};

export type GetCarModelResponse = {
    id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
    brand_id?: number;
    brand_name?: string;
};

export type SingleCarBrandResponse = {
    id: number;
    brandName: string;
};

export type GetAllToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type GetAllToolsResponses = {
    /**
     * OK
     */
    200: Array<SingleToolResponse>;
};

export type GetAllToolsResponse = GetAllToolsResponses[keyof GetAllToolsResponses];

export type CreateToolData = {
    body: CreateToolRequest;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type CreateToolResponses = {
    /**
     * OK
     */
    200: SingleToolResponse;
};

export type CreateToolResponse = CreateToolResponses[keyof CreateToolResponses];

export type GetAllRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/record';
};

export type GetAllRecordsResponses = {
    /**
     * OK
     */
    200: Array<GetRecordResponse>;
};

export type GetAllRecordsResponse = GetAllRecordsResponses[keyof GetAllRecordsResponses];

export type CreateRecordData = {
    body: CreateRecordRequest;
    path?: never;
    query?: never;
    url: '/api/record';
};

export type CreateRecordResponses = {
    /**
     * OK
     */
    200: CreateRecordResponse;
};

export type CreateRecordResponse2 = CreateRecordResponses[keyof CreateRecordResponses];

export type CreateMechanicalConditionData = {
    body: CreateMechanicalConditionRequest;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition';
};

export type CreateMechanicalConditionResponses = {
    /**
     * OK
     */
    200: CreateMechanicalConditionResponse;
};

export type CreateMechanicalConditionResponse2 = CreateMechanicalConditionResponses[keyof CreateMechanicalConditionResponses];

export type GetAllMechanicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type GetAllMechanicsResponses = {
    /**
     * OK
     */
    200: Array<MechanicInfo>;
};

export type GetAllMechanicsResponse = GetAllMechanicsResponses[keyof GetAllMechanicsResponses];

export type CreateMechanicData = {
    body: CreateMechanicRequest;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type CreateMechanicResponses = {
    /**
     * OK
     */
    200: CreateMechanicResponse;
};

export type CreateMechanicResponse2 = CreateMechanicResponses[keyof CreateMechanicResponses];

export type GetAllClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type GetAllClientsResponses = {
    /**
     * OK
     */
    200: Array<ClientInfo>;
};

export type GetAllClientsResponse = GetAllClientsResponses[keyof GetAllClientsResponses];

export type CreateClientData = {
    body: CreateClientRequest;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type CreateClientResponses = {
    /**
     * OK
     */
    200: CreateClientResponse;
};

export type CreateClientResponse2 = CreateClientResponses[keyof CreateClientResponses];

export type GetAllCheckInFullData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/checkin';
};

export type GetAllCheckInFullResponses = {
    /**
     * OK
     */
    200: Array<GetCheckInBasicResponse>;
};

export type GetAllCheckInFullResponse = GetAllCheckInFullResponses[keyof GetAllCheckInFullResponses];

export type CreateCheckInData = {
    body: CreateCheckInRequest;
    path?: never;
    query?: never;
    url: '/api/checkin';
};

export type CreateCheckInResponses = {
    /**
     * OK
     */
    200: CreateCheckInResponse;
};

export type CreateCheckInResponse2 = CreateCheckInResponses[keyof CreateCheckInResponses];

export type GetAllCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type GetAllCarsResponses = {
    /**
     * OK
     */
    200: Array<GetCarResponse>;
};

export type GetAllCarsResponse = GetAllCarsResponses[keyof GetAllCarsResponses];

export type CreateCarData = {
    body: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type CreateCarResponses = {
    /**
     * OK
     */
    200: CreateCarResponse;
};

export type CreateCarResponse2 = CreateCarResponses[keyof CreateCarResponses];

export type GetAllCarModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type GetAllCarModelsResponses = {
    /**
     * OK
     */
    200: Array<GetCarModelResponse>;
};

export type GetAllCarModelsResponse = GetAllCarModelsResponses[keyof GetAllCarModelsResponses];

export type CreateCarModelData = {
    body: CreateCarModelRequest;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type CreateCarModelResponses = {
    /**
     * OK
     */
    200: CreateCarModelResponse;
};

export type CreateCarModelResponse2 = CreateCarModelResponses[keyof CreateCarModelResponses];

export type GetAllCarBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type GetAllCarBrandsResponses = {
    /**
     * OK
     */
    200: Array<SingleCarBrandResponse>;
};

export type GetAllCarBrandsResponse = GetAllCarBrandsResponses[keyof GetAllCarBrandsResponses];

export type CreateMechanic1Data = {
    body: CreateCarBrandRequest;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type CreateMechanic1Responses = {
    /**
     * OK
     */
    200: CreateCarBrandResponse;
};

export type CreateMechanic1Response = CreateMechanic1Responses[keyof CreateMechanic1Responses];

export type GetInteriorConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/interior';
};

export type GetInteriorConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetInteriorConditionsResponse = GetInteriorConditionsResponses[keyof GetInteriorConditionsResponses];

export type GetExteriorConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/exterior';
};

export type GetExteriorConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetExteriorConditionsResponse = GetExteriorConditionsResponses[keyof GetExteriorConditionsResponses];

export type GetElectricalConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition/electrical';
};

export type GetElectricalConditionsResponses = {
    /**
     * OK
     */
    200: Array<SingleMechanicalCondition>;
};

export type GetElectricalConditionsResponse = GetElectricalConditionsResponses[keyof GetElectricalConditionsResponses];

export type GetCheckInFullData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/checkin/{id}/full';
};

export type GetCheckInFullResponses = {
    /**
     * OK
     */
    200: GetCheckInFullResponse;
};

export type GetCheckInFullResponse2 = GetCheckInFullResponses[keyof GetCheckInFullResponses];

export type GetCarFullByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car/{id}';
};

export type GetCarFullByIdResponses = {
    /**
     * OK
     */
    200: GetCarFullResponse;
};

export type GetCarFullByIdResponse = GetCarFullByIdResponses[keyof GetCarFullByIdResponses];

export type GetAllPatentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car/patents';
};

export type GetAllPatentsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetAllPatentsResponse = GetAllPatentsResponses[keyof GetAllPatentsResponses];

export type GetCarFullByPatentData = {
    body?: never;
    path: {
        patent: string;
    };
    query?: never;
    url: '/api/car/by-patent/{patent}';
};

export type GetCarFullByPatentResponses = {
    /**
     * OK
     */
    200: GetCarFullResponse;
};

export type GetCarFullByPatentResponse = GetCarFullByPatentResponses[keyof GetCarFullByPatentResponses];

export type GetCarModelData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car-model/{id}';
};

export type GetCarModelResponses = {
    /**
     * OK
     */
    200: GetCarModelResponse;
};

export type GetCarModelResponse2 = GetCarModelResponses[keyof GetCarModelResponses];
