// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateToolRequest = {
    tool_name?: string;
};

export type CreateToolResponse = {
    id?: number;
    tool_name?: string;
};

export type CreateRecordRequest = {
    reason?: string;
    car_id?: number;
    client_info_id?: number;
    mechanic_info_id?: number;
};

export type CreateRecordResponse = {
    id?: number;
    car_id?: number;
    client_info_id?: number;
    mechanic_info_id?: number;
};

export type CreateMechanicalConditionRequest = {
    part_name?: string;
    part_condition_state?: string;
    condition_type?: string;
};

export type CreateMechanicalConditionResponse = {
    id?: number;
    part_name?: string;
    part_condition_state?: string;
    condition_type?: string;
};

export type CreateMechanicRequest = {
    first_name?: string;
    last_name?: string;
    registration_number?: string;
};

export type CreateMechanicResponse = {
    id?: number;
    registration_number?: string;
};

export type CreateClientRequest = {
    first_name?: string;
    last_name?: string;
    email_address?: string;
    address?: string;
    cellphone_number?: string;
};

export type CreateClientResponse = {
    id?: number;
    cellphone_name?: string;
};

export type CreateCarRequest = {
    vin?: string;
    license_plate?: string;
    model_id?: number;
};

export type CreateCarResponse = {
    id?: number;
    license_plate?: string;
};

export type CreateCarModelRequest = {
    model_name?: string;
    model_type?: string;
    model_year?: number;
    brand_id?: number;
};

export type CreateCarModelResponse = {
    id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
};

export type CreateCarBrandRequest = {
    brand_name?: string;
};

export type CreateCarBrandResponse = {
    id?: number;
    registration_number?: string;
};

export type GetToolResponse = {
    id?: number;
    tool_name?: string;
};

export type GetRecordResponse = {
    reason?: string;
    car_license_plate?: string;
    client_first_name?: string;
    mechanic_first_name?: string;
};

export type MechanicInfo = {
    id?: number;
    firstName?: string;
    lastName?: string;
    registrationNumber?: string;
};

export type ClientInfo = {
    id?: number;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    address?: string;
    cellphoneNumber?: string;
};

export type GetCarResponse = {
    id?: number;
    vin?: string;
    license_plate?: string;
    model_id?: number;
    model_name?: string;
};

export type GetCarFullResponse = {
    id?: number;
    vin?: string;
    license_plate?: string;
    model_id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
    brand_id?: number;
    brand_name?: string;
};

export type GetCarModelResponse = {
    id?: number;
    model_name?: string;
    model_type?: string;
    model_year?: number;
    brand_id?: number;
    brand_name?: string;
};

export type GetCarBrandRepsonse = {
    id?: number;
    brand_name?: string;
};

export type GetAllToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type GetAllToolsResponses = {
    /**
     * OK
     */
    200: Array<GetToolResponse>;
};

export type GetAllToolsResponse = GetAllToolsResponses[keyof GetAllToolsResponses];

export type CreateToolData = {
    body: CreateToolRequest;
    path?: never;
    query?: never;
    url: '/api/tool';
};

export type CreateToolResponses = {
    /**
     * OK
     */
    200: CreateToolResponse;
};

export type CreateToolResponse2 = CreateToolResponses[keyof CreateToolResponses];

export type GetAllRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/record';
};

export type GetAllRecordsResponses = {
    /**
     * OK
     */
    200: Array<GetRecordResponse>;
};

export type GetAllRecordsResponse = GetAllRecordsResponses[keyof GetAllRecordsResponses];

export type CreateRecordData = {
    body: CreateRecordRequest;
    path?: never;
    query?: never;
    url: '/api/record';
};

export type CreateRecordResponses = {
    /**
     * OK
     */
    200: CreateRecordResponse;
};

export type CreateRecordResponse2 = CreateRecordResponses[keyof CreateRecordResponses];

export type CreateMechanicalConditionData = {
    body: CreateMechanicalConditionRequest;
    path?: never;
    query?: never;
    url: '/api/mechanical-condition';
};

export type CreateMechanicalConditionResponses = {
    /**
     * OK
     */
    200: CreateMechanicalConditionResponse;
};

export type CreateMechanicalConditionResponse2 = CreateMechanicalConditionResponses[keyof CreateMechanicalConditionResponses];

export type GetAllMechanicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type GetAllMechanicsResponses = {
    /**
     * OK
     */
    200: Array<MechanicInfo>;
};

export type GetAllMechanicsResponse = GetAllMechanicsResponses[keyof GetAllMechanicsResponses];

export type CreateMechanicData = {
    body: CreateMechanicRequest;
    path?: never;
    query?: never;
    url: '/api/mechanic';
};

export type CreateMechanicResponses = {
    /**
     * OK
     */
    200: CreateMechanicResponse;
};

export type CreateMechanicResponse2 = CreateMechanicResponses[keyof CreateMechanicResponses];

export type GetAllClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type GetAllClientsResponses = {
    /**
     * OK
     */
    200: Array<ClientInfo>;
};

export type GetAllClientsResponse = GetAllClientsResponses[keyof GetAllClientsResponses];

export type CreateClientData = {
    body: CreateClientRequest;
    path?: never;
    query?: never;
    url: '/api/client-info';
};

export type CreateClientResponses = {
    /**
     * OK
     */
    200: CreateClientResponse;
};

export type CreateClientResponse2 = CreateClientResponses[keyof CreateClientResponses];

export type GetAllCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type GetAllCarsResponses = {
    /**
     * OK
     */
    200: Array<GetCarResponse>;
};

export type GetAllCarsResponse = GetAllCarsResponses[keyof GetAllCarsResponses];

export type CreateCarData = {
    body: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/car';
};

export type CreateCarResponses = {
    /**
     * OK
     */
    200: CreateCarResponse;
};

export type CreateCarResponse2 = CreateCarResponses[keyof CreateCarResponses];

export type GetAllCarModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type GetAllCarModelsResponses = {
    /**
     * OK
     */
    200: Array<GetCarModelResponse>;
};

export type GetAllCarModelsResponse = GetAllCarModelsResponses[keyof GetAllCarModelsResponses];

export type CreateCarModelData = {
    body: CreateCarModelRequest;
    path?: never;
    query?: never;
    url: '/api/car-model';
};

export type CreateCarModelResponses = {
    /**
     * OK
     */
    200: CreateCarModelResponse;
};

export type CreateCarModelResponse2 = CreateCarModelResponses[keyof CreateCarModelResponses];

export type GetAllCarBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type GetAllCarBrandsResponses = {
    /**
     * OK
     */
    200: Array<GetCarBrandRepsonse>;
};

export type GetAllCarBrandsResponse = GetAllCarBrandsResponses[keyof GetAllCarBrandsResponses];

export type CreateMechanic1Data = {
    body: CreateCarBrandRequest;
    path?: never;
    query?: never;
    url: '/api/car-brand';
};

export type CreateMechanic1Responses = {
    /**
     * OK
     */
    200: CreateCarBrandResponse;
};

export type CreateMechanic1Response = CreateMechanic1Responses[keyof CreateMechanic1Responses];

export type GetCarFullData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car/{id}';
};

export type GetCarFullResponses = {
    /**
     * OK
     */
    200: GetCarFullResponse;
};

export type GetCarFullResponse2 = GetCarFullResponses[keyof GetCarFullResponses];

export type GetCarModelData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/car-model/{id}';
};

export type GetCarModelResponses = {
    /**
     * OK
     */
    200: GetCarModelResponse;
};

export type GetCarModelResponse2 = GetCarModelResponses[keyof GetCarModelResponses];
